Repository UBC-MDS/DSCI-532_2024_4_crime-tracker, pull requests merged in 2024-04, with the labels that each got.

#25 First draft of the App layout
  data/processed/crimedata_processed.csv
  src/app.py
Labels: Code

#24 deployment-setup
  environment.yml
  requirements.txt
Labels: deployment

#30 Updated new layout in src/app.py
  src/app.py
Labels: Code

#31 16 app design line chart and pie chart
  src/app.py
Labels: Code

#33 Updated README.md to included installation and usage instruction.
  README.md
Labels: documentation

#37 Displaying gif
  README.md
Labels: documentation

#50 Updated dashboard layout in app.py.
  src/app.py
Labels: Code

#81 Updated components.py and callback to make our crime count card dynamic.
  src/callbacks.py
  src/components.py
Labels: Code

#82 79 improve layout
  src/app.py
  src/assets/style.css
  src/callbacks.py
  src/components.py
Labels: Code

#89 Updated README.md to reflect the changes made.
  README.md
Labels: documentation
